# Generated by Django 2.2.19 on 2022-05-25 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220525_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractions',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='useractions',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
