# Generated by Django 2.2.19 on 2022-05-22 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='function_name',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Название функции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.Category', verbose_name='Категория'),
        ),
    ]
