# Generated by Django 2.2.19 on 2022-05-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220524_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='comment',
        ),
    ]
